### ISSUE TITLE
Result of K-means++ is erratic

### ISSUE THREAD

**Issue by jensen888** [siddheshk/Faster-Kmeans#1]
While result of  SKlearn's K_means_elkan is all the same however much times you try. 
So it's what caused the result of kpp.py+triangleInequality.py changable.

**Comment by siddheshk** [comment]
The Kmeans++ algorithm (kpp.py) we used doesn't select the same initial seeds everytime. If you force that condition you will get the same result everytime with kpp.py+triangleInequality.
